- name: ROBOSIBLE
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-05e5bd14656ebdaf3
    zone_id: Z0212707MY585LOOEFGA
    domain: kriiishmatic.fun
    aws_region: us-east-1
    instance_name: 
    - mongod

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        image_id: "{{ ami_id }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        tags:
         name : "{{ item }}"
      loop: "{{ instance_name }}"
      register: ec2_info

    # - name: Reading output
    #   ansible.builtin.debug:
    #     msg: "{{ ec2_info }}"
  
    - name: Public searching in the output
      ansible.builtin.debug:
        msg: "{{ item.instances[0].public_ip_address }}"
      loop: "{ ec2_info.results }}"

    - name: Private Ip search in ouptput
      ansible.builtin.debug:
        msg: "{{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_info.results }}"