- name: ROBOSIBLE
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-05e5bd14656ebdaf3
    zone_id: Z0212707MY585LOOEFGA
    domain: kriiishmatic.fun
    aws_region: us-east-1
    instance_name: 
    - mongod

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
        Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    # - name: Reading output
    #   ansible.builtin.debug:
    #     msg: "{{ ec2_info }}"
  
    - name: print public_ip
      ansible.builtin.debug: 
        msg: "{{ item.instances[0].public_ip_address }}"
      loop: "{{ ec2_output.results }}"

    - name: print private_ip
      ansible.builtin.debug: 
        msg: "{{ item.instances[0].private_ip_address }}"
      loop: "{{ ec2_output.results }}"